"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestMaterialDesignColors,
	#superclass : #PackageManifest,
	#category : 'Material-Design-Colors'
}

{ #category : #'meta-data' }
ManifestMaterialDesignColors class >> description [ ^ 'I am a package containing extensions to the Pharo colors following Material Design recommendations. 

For more info see:
https://material.io/guidelines/style/color.html'
]
